# Automatically generated by pb2py
# fmt: off
import protobuf as p

if __debug__:
    try:
        from typing import Dict, List, Optional  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class NEM2Mosaic(p.MessageType):

    def __init__(
        self,
        *,
        id: Optional[str] = None,
        amount: Optional[str] = None,
    ) -> None:
        self.id = id
        self.amount = amount

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('id', p.UnicodeType, None),
            2: ('amount', p.UnicodeType, None),
        }
