# Automatically generated by pb2py
# fmt: off
import protobuf as p

if __debug__:
    try:
        from typing import Dict, List, Optional  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class NEM2MosaicMetadataTransaction(p.MessageType):

    def __init__(
        self,
        *,
        target_public_key: Optional[str] = None,
        scoped_metadata_key: Optional[str] = None,
        target_mosaic_id: Optional[str] = None,
        value_size_delta: Optional[int] = None,
        value_size: Optional[int] = None,
        value: Optional[str] = None,
    ) -> None:
        self.target_public_key = target_public_key
        self.scoped_metadata_key = scoped_metadata_key
        self.target_mosaic_id = target_mosaic_id
        self.value_size_delta = value_size_delta
        self.value_size = value_size
        self.value = value

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('target_public_key', p.UnicodeType, None),
            2: ('scoped_metadata_key', p.UnicodeType, None),
            3: ('target_mosaic_id', p.UnicodeType, None),
            4: ('value_size_delta', p.UVarintType, None),
            5: ('value_size', p.UVarintType, None),
            6: ('value', p.UnicodeType, None),
        }
