# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .NEM2AccountAddressRestrictionTransaction import (
    NEM2AccountAddressRestrictionTransaction,
)
from .NEM2AccountLinkTransaction import NEM2AccountLinkTransaction
from .NEM2AccountMetadataTransaction import NEM2AccountMetadataTransaction
from .NEM2AccountMosaicRestrictionTransaction import (
    NEM2AccountMosaicRestrictionTransaction,
)
from .NEM2AccountOperationRestrictionTransaction import (
    NEM2AccountOperationRestrictionTransaction,
)
from .NEM2AddressAliasTransaction import NEM2AddressAliasTransaction
from .NEM2AggregateTransaction import NEM2AggregateTransaction
from .NEM2HashLockTransaction import NEM2HashLockTransaction
from .NEM2MosaicAddressRestrictionTransaction import (
    NEM2MosaicAddressRestrictionTransaction,
)
from .NEM2MosaicAliasTransaction import NEM2MosaicAliasTransaction
from .NEM2MosaicDefinitionTransaction import NEM2MosaicDefinitionTransaction
from .NEM2MosaicGlobalRestrictionTransaction import (
    NEM2MosaicGlobalRestrictionTransaction,
)
from .NEM2MosaicMetadataTransaction import NEM2MosaicMetadataTransaction
from .NEM2MosaicSupplyChangeTransaction import NEM2MosaicSupplyChangeTransaction
from .NEM2MultisigModificationTransaction import NEM2MultisigModificationTransaction
from .NEM2NamespaceMetadataTransaction import NEM2NamespaceMetadataTransaction
from .NEM2NamespaceRegistrationTransaction import NEM2NamespaceRegistrationTransaction
from .NEM2SecretLockTransaction import NEM2SecretLockTransaction
from .NEM2SecretProofTransaction import NEM2SecretProofTransaction
from .NEM2TransactionCommon import NEM2TransactionCommon
from .NEM2TransferTransaction import NEM2TransferTransaction

if __debug__:
    try:
        from typing import Dict, List, Optional  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class NEM2SignTx(p.MessageType):
    MESSAGE_WIRE_TYPE = 806

    def __init__(
        self,
        *,
        address_n: Optional[List[int]] = None,
        transaction: Optional[NEM2TransactionCommon] = None,
        multisig: Optional[NEM2TransactionCommon] = None,
        transfer: Optional[NEM2TransferTransaction] = None,
        generation_hash: Optional[str] = None,
        cosigning: Optional[str] = None,
        mosaic_definition: Optional[NEM2MosaicDefinitionTransaction] = None,
        mosaic_supply: Optional[NEM2MosaicSupplyChangeTransaction] = None,
        namespace_registration: Optional[NEM2NamespaceRegistrationTransaction] = None,
        address_alias: Optional[NEM2AddressAliasTransaction] = None,
        aggregate: Optional[NEM2AggregateTransaction] = None,
        namespace_metadata: Optional[NEM2NamespaceMetadataTransaction] = None,
        mosaic_metadata: Optional[NEM2MosaicMetadataTransaction] = None,
        account_metadata: Optional[NEM2AccountMetadataTransaction] = None,
        mosaic_alias: Optional[NEM2MosaicAliasTransaction] = None,
        hash_lock: Optional[NEM2HashLockTransaction] = None,
        secret_lock: Optional[NEM2SecretLockTransaction] = None,
        secret_proof: Optional[NEM2SecretProofTransaction] = None,
        multisig_modification: Optional[NEM2MultisigModificationTransaction] = None,
        account_address_restriction: Optional[NEM2AccountAddressRestrictionTransaction] = None,
        account_mosaic_restriction: Optional[NEM2AccountMosaicRestrictionTransaction] = None,
        account_operation_restriction: Optional[NEM2AccountOperationRestrictionTransaction] = None,
        account_link: Optional[NEM2AccountLinkTransaction] = None,
        mosaic_global_restriction: Optional[NEM2MosaicGlobalRestrictionTransaction] = None,
        mosaic_address_restriction: Optional[NEM2MosaicAddressRestrictionTransaction] = None,
    ) -> None:
        self.address_n = address_n if address_n is not None else []
        self.transaction = transaction
        self.multisig = multisig
        self.transfer = transfer
        self.generation_hash = generation_hash
        self.cosigning = cosigning
        self.mosaic_definition = mosaic_definition
        self.mosaic_supply = mosaic_supply
        self.namespace_registration = namespace_registration
        self.address_alias = address_alias
        self.aggregate = aggregate
        self.namespace_metadata = namespace_metadata
        self.mosaic_metadata = mosaic_metadata
        self.account_metadata = account_metadata
        self.mosaic_alias = mosaic_alias
        self.hash_lock = hash_lock
        self.secret_lock = secret_lock
        self.secret_proof = secret_proof
        self.multisig_modification = multisig_modification
        self.account_address_restriction = account_address_restriction
        self.account_mosaic_restriction = account_mosaic_restriction
        self.account_operation_restriction = account_operation_restriction
        self.account_link = account_link
        self.mosaic_global_restriction = mosaic_global_restriction
        self.mosaic_address_restriction = mosaic_address_restriction

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('transaction', NEM2TransactionCommon, None),
            2: ('multisig', NEM2TransactionCommon, None),
            3: ('transfer', NEM2TransferTransaction, None),
            4: ('generation_hash', p.UnicodeType, None),
            5: ('address_n', p.UVarintType, p.FLAG_REPEATED),
            6: ('cosigning', p.UnicodeType, None),
            7: ('mosaic_definition', NEM2MosaicDefinitionTransaction, None),
            8: ('mosaic_supply', NEM2MosaicSupplyChangeTransaction, None),
            9: ('namespace_registration', NEM2NamespaceRegistrationTransaction, None),
            10: ('address_alias', NEM2AddressAliasTransaction, None),
            11: ('aggregate', NEM2AggregateTransaction, None),
            12: ('namespace_metadata', NEM2NamespaceMetadataTransaction, None),
            13: ('mosaic_metadata', NEM2MosaicMetadataTransaction, None),
            14: ('account_metadata', NEM2AccountMetadataTransaction, None),
            15: ('mosaic_alias', NEM2MosaicAliasTransaction, None),
            16: ('hash_lock', NEM2HashLockTransaction, None),
            17: ('secret_lock', NEM2SecretLockTransaction, None),
            18: ('secret_proof', NEM2SecretProofTransaction, None),
            19: ('multisig_modification', NEM2MultisigModificationTransaction, None),
            21: ('account_address_restriction', NEM2AccountAddressRestrictionTransaction, None),
            22: ('account_mosaic_restriction', NEM2AccountMosaicRestrictionTransaction, None),
            23: ('account_operation_restriction', NEM2AccountOperationRestrictionTransaction, None),
            24: ('account_link', NEM2AccountLinkTransaction, None),
            25: ('mosaic_global_restriction', NEM2MosaicGlobalRestrictionTransaction, None),
            26: ('mosaic_address_restriction', NEM2MosaicAddressRestrictionTransaction, None),
        }
