# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .NEM2Mosaic import NEM2Mosaic

if __debug__:
    try:
        from typing import Dict, List, Optional  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class NEM2HashLockTransaction(p.MessageType):

    def __init__(
        self,
        *,
        mosaic: Optional[NEM2Mosaic] = None,
        duration: Optional[int] = None,
        hash: Optional[str] = None,
    ) -> None:
        self.mosaic = mosaic
        self.duration = duration
        self.hash = hash

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('mosaic', NEM2Mosaic, None),
            2: ('duration', p.UVarintType, None),
            3: ('hash', p.UnicodeType, None),
        }
