# Automatically generated by pb2py
# fmt: off
if __debug__:
    try:
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass

ALLOW_INCOMING_ADDRESS: Literal[1] = 1
ALLOW_MOSAIC: Literal[2] = 2
ALLOW_INCOMING_TRANSACTION_TYPE: Literal[4] = 4
ALLOW_OUTGOING_ADDRESS: Literal[16385] = 16385
ALLOW_OUTGOING_TRANSACTION_TYPE: Literal[16388] = 16388
BLOCK_INCOMING_ADDRESS: Literal[32769] = 32769
BLOCK_MOSAIC: Literal[32770] = 32770
BLOCK_INCOMING_TRANSACTION_TYPE: Literal[32772] = 32772
BLOCK_OUTGOING_ADDRESS: Literal[49153] = 49153
BLOCK_OUTGOING_TRANSACTION_TYPE: Literal[49156] = 49156
