# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

from .NEM2Address import NEM2Address

if __debug__:
    try:
        from typing import Dict, List, Optional  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class NEM2MosaicAddressRestrictionTransaction(p.MessageType):

    def __init__(
        self,
        *,
        mosaic_id: Optional[str] = None,
        restriction_key: Optional[str] = None,
        previous_restriction_value: Optional[str] = None,
        new_restriction_value: Optional[str] = None,
        target_address: Optional[NEM2Address] = None,
    ) -> None:
        self.mosaic_id = mosaic_id
        self.restriction_key = restriction_key
        self.previous_restriction_value = previous_restriction_value
        self.new_restriction_value = new_restriction_value
        self.target_address = target_address

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('mosaic_id', p.UnicodeType, None),
            2: ('restriction_key', p.UnicodeType, None),
            3: ('previous_restriction_value', p.UnicodeType, None),
            4: ('new_restriction_value', p.UnicodeType, None),
            5: ('target_address', NEM2Address, None),
        }
