# Automatically generated by pb2py
# fmt: off
if __debug__:
    try:
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass

SHA3_256: Literal[0] = 0
KECCAK_256: Literal[1] = 1
HASH_160: Literal[2] = 2
HASH_256: Literal[3] = 3
