# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

if __debug__:
    try:
        from typing import Dict, List, Optional  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class NEM2MultisigModificationTransaction(p.MessageType):

    def __init__(
        self,
        *,
        public_key_additions: Optional[List[str]] = None,
        public_key_deletions: Optional[List[str]] = None,
        min_approval_delta: Optional[int] = None,
        min_removal_delta: Optional[int] = None,
    ) -> None:
        self.public_key_additions = public_key_additions if public_key_additions is not None else []
        self.public_key_deletions = public_key_deletions if public_key_deletions is not None else []
        self.min_approval_delta = min_approval_delta
        self.min_removal_delta = min_removal_delta

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('min_approval_delta', p.UVarintType, None),
            2: ('min_removal_delta', p.UVarintType, None),
            3: ('public_key_additions', p.UnicodeType, p.FLAG_REPEATED),
            4: ('public_key_deletions', p.UnicodeType, p.FLAG_REPEATED),
        }
