# Automatically generated by pb2py
# fmt: off
if __debug__:
    try:
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass

MAIN_NET: Literal[104] = 104
TEST_NET: Literal[152] = 152
MIJIN: Literal[96] = 96
MIJIN_TEST: Literal[144] = 144
