# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

from .NEM2Address import NEM2Address
from .NEM2Mosaic import NEM2Mosaic

if __debug__:
    try:
        from typing import Dict, List, Optional  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
        EnumTypeNEM2LockHashAlgorithm = Literal[0, 1, 2, 3]
    except ImportError:
        pass


class NEM2SecretLockTransaction(p.MessageType):

    def __init__(
        self,
        *,
        secret: Optional[str] = None,
        mosaic: Optional[NEM2Mosaic] = None,
        duration: Optional[int] = None,
        hash_algorithm: EnumTypeNEM2LockHashAlgorithm = 0,
        recipient_address: Optional[NEM2Address] = None,
    ) -> None:
        self.secret = secret
        self.mosaic = mosaic
        self.duration = duration
        self.hash_algorithm = hash_algorithm
        self.recipient_address = recipient_address

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('secret', p.UnicodeType, None),
            2: ('mosaic', NEM2Mosaic, None),
            3: ('duration', p.UVarintType, None),
            4: ('hash_algorithm', p.EnumType("NEM2LockHashAlgorithm", (0, 1, 2, 3)), 0),  # default=SHA3_256
            5: ('recipient_address', NEM2Address, None),
        }
